### Listar
GET http://localhost:8000/users

### Criar
POST http://localhost:8000/user
Content-Type: application/json

{
    "username": "Juca Neves",
    "password": "teste123",
    "email": "juca.neves@gmail.com"
}

### Recuperar
GET http://localhost:8000/user/bba7882c-fbfc-4e21-821b-1b75ca08e872
Content-Type: application/json

### Atualizar
PUT http://localhost:8000/user/3e4d52e5-2fc3-4452-b1c0-284e78e6aa34
Content-Type: application/json

{
    "username": "Juca Neves",
    "password": "teste123",
    "email": "juca.neves@gmail.com"
}

### Deletar
DELETE http://localhost:8000/user/f547eab9-49d5-4f39-9324-2eb80d9c9fe3

### Create Read Update Delete